rootProject.name = "back-end-kotlin"
include("module-common-kotlin")
include("module-common-file-kotlin")
include("module-security-base-kotlin")
include("module-security-kotlin")
include("feature-domain-device-kotlin")
include("feature-service-device-kotlin")
include("server-device-kotlin")
include("feature-domain-punishment-kotlin")
include("feature-service-punishment-kotlin")
include("server-punishment-kotlin")