services:
  mysql:
    image: mysql:latest
    ports:
      - 19373:3306
    networks:
      - base
    environment:
      TZ: Asia/Shanghai
      MYSQL_DATABASE: iot_test
      MYSQL_ROOT_PASSWORD: 135246xyx
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    security_opt:
      - seccomp:unconfined
networks:
  base:
    name: iot_network
volumes:
  mysql-data: