server:
  port: 8081
  servlet:
    context-path: /punishment
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/punishment_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 135246xyx
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 30000
      max-lifetime: 300000
      minimum-idle: 10
      maximum-pool-size: 50
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  cache:
    type: redis
  redis:
    host: redis-dev
    port: 6379
    password: redis_xyx_001
#actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
host: punishment.onlyfast.com.cn